name: Feature Request Custom
description: Feature Request With Custom Field
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: input
    id: contact
    attributes:
      label: Contact Info
      description: How can we reach you?
      placeholder: email@example.com
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: Describe the feature details
      placeholder: Describe the feature detail...
      value: "value 1"
