name: KPI Calculator
description: Nhập các số liệu để tự động tính toán KPI
title: "[KPI] Tính KPI cho dự án"
labels: ["kpi"]
body:
  - type: input
    id: number_a
    attributes:
      label: Nhập số A
      description: Số đầu tiên cần tính
      placeholder: "Ví dụ: 10"
    validations:
      required: true

  - type: input
    id: number_b
    attributes:
      label: Nhập số B
      description: Số thứ hai cần tính
      placeholder: "Ví dụ: 20"
    validations:
      required: true

  - type: input
    id: number_c
    attributes:
      label: Nhập số C
      description: Số thứ ba cần tính
      placeholder: "Ví dụ: 30"
    validations:
      required: false
