name: "Sample Clean Issue"
description: "テンプレート: 本票の更新履歴 (Sample Clean Issue Template)"
title: "[本票] <タイトルを入力>"
labels: ["documentation", "update-history"]
body:
  - type: markdown
    attributes:
      value: |
        # 本票の更新履歴
        以下の表に従って、更新履歴を記入してください。
  - type: textarea
    id: update-history
    attributes:
      label: 更新履歴
      description: |
        更新履歴をマークダウン形式のテーブルで記入してください。
        例:
        | 項番 | 見直し項目 | 見直し理由 | 見直し内容 | 更新日 | 承認者 | 更新者 |
        |:---|:---|:---|:---|:---|:---|:---|
        | 1 | 〇〇の修正 | 仕様変更 | 〇〇を△△に変更 | 2025-09-09 | 山田 | 佐藤 |
    validations:
      required: true
  - type: input
    id: pj-code
    attributes:
      label: PJコード
      description: プロジェクトコードを入力してください。
    validations:
      required: false
  - type: input
    id: pj-name
    attributes:
      label: PJ名
      description: プロジェクト名を入力してください。
    validations:
      required: false
  - type: input
    id: department
    attributes:
      label: 部門名
      description: 部門名を入力してください。
    validations:
      required: false
  - type: input
    id: division
    attributes:
      label: 事業部
      description: 事業部名を入力してください。
    validations:
      required: false
