name: Bug Report Custom
description: Bug Report With Custom Field
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: contact
    attributes:
      label: Contact Info
      description: How can we reach you?
      placeholder: email@example.com
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: Describe the bug details
      placeholder: Describe the bug detail...
      value: "value 1"
