name: "sample"
description: "sample"
title: "[sample]"
labels: ["log", "work-time"]
assignees: []
body:
  - type: input
    id: issue_id
    attributes:
      label: "Issue"
      description: "関連するIssue番号を入力してください（任意）"
      placeholder: "例：1234"
    onclick:
      focus: true
    style:
      focusBorderColor: blue
    validations:
      required: false

  - type: input
    id: time_spent
    attributes:
      label: "作業時間 (h) *"
      description: "作業にかかった時間を入力してください (例：1.5)"
      placeholder: "例：2.0"
    validations:
      required: true
 
