---
name: Custom Issue
about: Create a custom issue using the sample template
labels: bug, enhancement
assignees: ''
---

## Description

<!-- Please describe the issue or feature request in detail. -->

## Steps to Reproduce / Implement

<!-- List the steps to reproduce the bug or implement the feature. -->

## Expected Behavior

<!-- What did you expect to happen? -->

## Actual Behavior

<!-- What actually happened? -->

## Additional Context

<!-- Add any other context or screenshots about the issue here. -->
