name: "本票の更新履歴"
description: "本票の更新履歴（更新履歴表）を記入してください。"
title: "[更新履歴] PJ名: <プロジェクト名> 事業部: <事業部名> 部門名: <部門名>"
labels: ["update-history"]
body:
  - type: markdown
    attributes:
      value: |
        ## 本票の更新履歴

        ※４版以降は、３版をコピーすること。

  - type: input
    id: pj_code
    attributes:
      label: PJコード
      description: プロジェクトコードを入力してください。
      placeholder: 例）PJ-001
    validations:
      required: false

  - type: input
    id: pj_name
    attributes:
      label: PJ名
      description: プロジェクト名を入力してください。
      placeholder: 例）コインゲーム
    validations:
      required: true

  - type: input
    id: division
    attributes:
      label: 事業部
      description: 事業部名を入力してください。
      placeholder: 例）AI事業部
    validations:
      required: false

  - type: input
    id: department
    attributes:
      label: 部門名
      description: 部門名を入力してください。
      placeholder: 例）開発部
    validations:
      required: false

  # --- 2版 更新履歴 từng dòng ---
  - type: markdown
    attributes:
      value: "### ２版 更新履歴 - 項番 1"

  - type: input
    id: update_2nd_1_date
    attributes:
      label: 更新日
    validations:
      required: false

  - type: input
    id: update_2nd_1_approver
    attributes:
      label: 承認者
    validations:
      required: false

  - type: input
    id: update_2nd_1_updater
    attributes:
      label: 更新者
    validations:
      required: false
  - type: input
    id: update_2nd_1_item
    attributes:
      label: 見直し項目
    validations:
      required: false

  - type: input
    id: update_2nd_1_reason
    attributes:
      label: 見直し理由
    validations:
      required: false

  - type: input
    id: update_2nd_1_content
    attributes:
      label: 見直し内容
    validations:
      required: false
  # --- 3版 更新履歴 từng dòng ---
  - type: markdown
    attributes:
      value: "### ３版 更新履歴 - 項番 1"

  - type: input
    id: update_3rd_1_date
    attributes:
      label: 更新日
    validations:
      required: false

  - type: input
    id: update_3rd_1_approver
    attributes:
      label: 承認者
    validations:
      required: false

  - type: input
    id: update_3rd_1_updater
    attributes:
      label: 更新者
    validations:
      required: false

  - type: input
    id: update_3rd_1_item
    attributes:
      label: 見直し項目
    validations:
      required: false

  - type: input
    id: update_3rd_1_reason
    attributes:
      label: 見直し理由
    validations:
      required: false

  - type: input
    id: update_3rd_1_content
    attributes:
      label: 見直し内容
    validations:
      required: false

  - type: textarea
    id: remarks
    attributes:
      label: 備考
      description: その他、特記事項があれば記入してください。
      placeholder: 例）特になし
