name: "働き方改革支援ソリューション 製品開発 レビュー"
description: "働き方見える化サービスPlus のレビュー用チケットテンプレート"
title: "[レビュー] 題名を入力してください"
labels: ["review", "quality-assurance"]
assignees: []
body:
  - type: input
    id: subject
    attributes:
      label: "題名 *"
      description: "チケットの題名を入力してください"
      placeholder: "例：レビュー指摘事項"
    validations:
      required: true

  - type: dropdown
    id: tracker
    attributes:
      label: "トラッカー *"
      description: "チケットの種別を選択してください"
      options:
        - レビュー
        - エピック
        - バグ
        - スプリント内バグ
        - リリーススプリントタスク
        - 機能
        - 課題
        - ストーリー
        - タスク
        - PJ課題
        - イベント
        - バグ(β)
        - 設計チェックリスト
        - 開発チェックリスト(サーバ)
        - 開発チェックリスト(エージェント)
        - 機能テストチェックリスト
        - 調査チェックリスト
        - 工数計測
        - 企画要望
        - 審査チェックリスト
      default: 0
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: "ステータス *"
      description: "チケットのステータスを選択してください"
      options:
        - TODO
        - DOING
        - DONE
      default: 0
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "優先度 *"
      description: "チケットの優先度を選択してください"
      options:
        - 低め
        - 通常
        - 高め
        - 急いで
        - 今すぐ
        - MUST
      default: 1
    validations:
      required: true

  - type: input
    id: parent_issue
    attributes:
      label: "親チケット"
      description: "親チケットのIDがある場合は入力してください"
      placeholder: "例：#123"

  - type: dropdown
    id: phase
    attributes:
      label: "フェーズ *"
      description: "レビュー対象の作業のフェーズを選択してください"
      options:
        - 00.要件定義
        - 10.設計
        - 20.オフショア開発
        - 20.国内製造
        - 30.国内受入れ
        - 40.機能テスト
        - 90.リリース
        - 99.2枚目以降のため管理外
      default: 0
    validations:
      required: true

  - type: dropdown
    id: review_status
    attributes:
      label: "レビューステータス *"
      description: "レビューの状況を選択してください"
      options:
        - 10.レビュー中
        - 20.レビュー反映待ち
        - 21.レビュー反映中
        - 31.レビュー反映確認待ち
        - 90.レビュー完了
        - 99.2枚目以降のため管理外
      default: 0
    validations:
      required: true

  - type: input
    id: repository_revision
    attributes:
      label: "リポジトリ・リビジョン番号"
      description: "製造（ソース）レビュー時の対象バージョンを記入する"
      placeholder: "例：r12345"

  - type: checkboxes
    id: reviewers
    attributes:
      label: "レビューア *"
      description: "レビューアを選択してください"
      options:
        - label: "Hoang Tran Duc"
        - label: "Huynh Tan Sy"
        - label: "Ly Hong Quy"
        - label: "Nguyen Hoang Lan"
        # ... (全員分追加)

  - type: checkboxes
    id: reviewees
    attributes:
      label: "レビューイ *"
      description: "レビューイを選択してください"
      options:
        - label: "Hoang Tran Duc"
        - label: "Huynh Tan Sy"
        - label: "Ly Hong Quy"
        - label: "Nguyen Hoang Lan"
        # ... (全員分追加)

  # 指摘事項（最大4件分）
  - type: textarea
    id: issue_1_description
    attributes:
      label: "指摘事項（問題点の内容）①"
      description: "指摘事項の内容を記入してください"
  - type: textarea
    id: issue_1_action
    attributes:
      label: "対応指針（処置内容）①"
      description: "対応指針を記入してください"
  - type: dropdown
    id: issue_1_type
    attributes:
      label: "区分①"
      options:
        - バグ
        - APバグ以外
        - 課題
        - 仕変(ﾕｰｻﾞ)
        - 仕変(内部)
        - コメント
        - 指摘誤り
  - type: dropdown
    id: issue_1_process
    attributes:
      label: "原因工程①"
      options:
        - 基本設計
        - 機能設計
        - 詳細設計
        - 製造
        - 単体ﾃｽﾄ
        - 受入ﾃｽﾄ
        - 機能ﾃｽﾄ
        - 結合ﾃｽﾄ
        - 総合ﾃｽﾄ
        - 運用ﾃｽﾄ
  - type: dropdown
    id: issue_1_cause
    attributes:
      label: "原因区分①"
      options:
        - 要求仕様書ﾐｽ
        - 設計漏れ
        - 設計誤り
        - 製造漏れ
        - 製造ﾛｼﾞｯｸﾐｽ
        - ｹｱﾚｽﾐｽ
        - 誤記
        - ﾌﾟﾛｸﾞﾗﾑ構造ﾐｽ
        - 製造ﾃﾞｰﾀ定義ﾐｽ
        - ﾃﾞｰﾀﾍﾞｰｽﾐｽ
        - ﾌｧｲﾙﾐｽ
        - 環境設定ﾐｽ
        - 統合ﾐｽ
        - ﾘﾘｰｽﾐｽ
        - 運用ﾐｽ
        - 操作ﾐｽ
        - OS等SW障害
        - HW障害
        - 原因不明
        - 過剰要求
        - 仕様通り
        - 仕変(ﾕｰｻﾞ)
        - 仕変(内部)
        - 仕様確認
        - 改善要望
        - クレーム
        - 計画変更
        - Ｑ＆Ａ
        - その他
        - 指摘誤り
  - type: dropdown
    id: issue_1_confirmer
    attributes:
      label: "処置確認者①"
      options:
        - Hoang Tran Duc
        - Huynh Tan Sy
        - Ly Hong Quy
        - Nguyen Hoang Lan
        # ... (全員分追加)
  - type: checkboxes
    id: issue_1_confirmed
    attributes:
      label: "処置確認済み①"
      options:
        - label: "確認済み"

  # Repeat for issue_2, issue_3, issue_4 as needed
