name: Auto Update Worklog Fields

on:
  issues:
    types: [labeled, unlabeled, closed]
  pull_request:
    types: [labeled, unlabeled, closed]

jobs:
  update-worklog-fields:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-set Work type based on labels
        uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: https://github.com/users/merl2801/projects/8
          github-token: ${{ secrets.PROJECT_TOKEN }}
          item-id: ${{ github.event.issue.node_id || github.event.pull_request.node_id }}
          field-keys: Work type
          field-values: |
            ${{ 
              contains(github.event.issue.labels.*.name, 'bug') && 'テスト' ||
              contains(github.event.issue.labels.*.name, 'enhancement') && '実装' ||
              contains(github.event.issue.labels.*.name, 'documentation') && '調査' ||
              contains(github.event.issue.labels.*.name, 'design') && '設計' ||
              github.event_name == 'pull_request' && 'コードレビュー' ||
              'その他'
            }}

  auto-assign-date:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - name: Set completion date
        uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: https://github.com/users/merl2801/projects/8
          github-token: ${{ secrets.PROJECT_TOKEN }}
          item-id: ${{ github.event.issue.node_id || github.event.pull_request.node_id }}
          field-keys: Date
          field-values: ${{ github.event.issue.closed_at || github.event.pull_request.closed_at }}
