# IMPORTANT: This workflow requires a Personal Access Token (PAT) with project access
# 1. Go to GitHub Settings > Developer Settings > Personal access tokens > Generate new token
# 2. Give it a name like "Project Automation"
# 3. Select scopes: repo, project
# 4. Copy the token
# 5. Go to your repository > Settings > Secrets and variables > Actions > New repository secret
# 6. Name: ADD_TO_PROJECT_PAT
# 7. Value: [paste your token]
#
# LABELS:
# - 'To Do': Default label for all new issues
# - 'Bug': Automatically added when title contains: bug, fix, error, crash
# - 'Feature': Automatically added when title contains: feature, add, new
# - 'Enhancement': Automatically added when title contains: improve, enhance, better
# - 'Game Design': Automatically added when title contains: design, level, character, graphic
name: Scrum Backlog Automation

on:
  issues:
    types: [opened, labeled]

# Add permissions needed for project access
permissions:
  issues: write
  repository-projects: write
  contents: read

jobs:
  auto-label-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Auto assign labels for new issues
        uses: actions/github-script@v7
        with:
          script: |
            // Game related labels
            const defaultLabels = ['To Do'];
            const issueTitleLower = context.payload.issue.title.toLowerCase();
            
            // Analyze issue title and content to determine appropriate labels
            if (issueTitleLower.includes('bug') || 
                issueTitleLower.includes('fix') || 
                issueTitleLower.includes('error') || 
                issueTitleLower.includes('crash')) {
              defaultLabels.push('Bug');
            }
            
            if (issueTitleLower.includes('feature') || 
                issueTitleLower.includes('add') || 
                issueTitleLower.includes('new')) {
              defaultLabels.push('Feature');
            }
            
            if (issueTitleLower.includes('improve') || 
                issueTitleLower.includes('enhance') || 
                issueTitleLower.includes('better')) {
              defaultLabels.push('Enhancement');
            }
            
            if (issueTitleLower.includes('design') || 
                issueTitleLower.includes('level') || 
                issueTitleLower.includes('character') ||
                issueTitleLower.includes('graphic')) {
              defaultLabels.push('Game Design');
            }
            
            const issue = context.payload.issue;
            
            // Only add labels if the issue doesn't have any
            if (issue.labels.length === 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: defaultLabels
              });
              console.log(`Added labels: ${defaultLabels.join(', ')}`);
            }

      # Use the official GitHub action for projects v2
      - name: Add issue to project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/users/merl2801/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
