name: Scrum Backlog Automation

on:
  issues:
    types: [opened, labeled]

jobs:
  auto-label-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Auto assign labels for new issues
        uses: actions/github-script@v7
        with:
          script: |
            const labelsToAdd = ['New Item', 'TODO'];
            const issue = context.payload.issue;

            if (issue.labels.length === 0) {
              await github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                labels: labelsToAdd
              });
            }

      - name: Move issue to New Item view (if using Projects v2)
        uses: actions/github-script@v7
        with:
          script: |
            // Requires project automation via GraphQL or API v4
            // Placeholder: GitHub Projects v2 automation not fully supported via REST yet
            console.log("Move to New Item view manually or via GitHub Project automation rules.");
